on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Create manifest.json
      run: |
        ver=$(basename "$GITHUB_REF")
        echo "Setting version $ver on manifest.json"
        echo "{\"version\": \"$ver\"}" >  cmd/hvm/version/manifest.json
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: ./cmd/hvm
